// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJPTnrEkS7wi8Rdf460GoZjp4VFLBaj-w',
    appId: '1:799126783379:web:2d01628b42ea8c14a3d466',
    messagingSenderId: '799126783379',
    projectId: 'animal-5e97a',
    authDomain: 'animal-5e97a.firebaseapp.com',
    storageBucket: 'animal-5e97a.appspot.com',
    measurementId: 'G-PQG84PL0BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArk5RbpET5HAOdkEThbONjHUYJv2U7SOM',
    appId: '1:799126783379:android:d544d3782b6f025ba3d466',
    messagingSenderId: '799126783379',
    projectId: 'animal-5e97a',
    storageBucket: 'animal-5e97a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEyrYeUOhIrnRMCEYmWEO8KXn-J-d8Pk0',
    appId: '1:799126783379:ios:adccb81706e2c9a3a3d466',
    messagingSenderId: '799126783379',
    projectId: 'animal-5e97a',
    storageBucket: 'animal-5e97a.appspot.com',
    iosBundleId: 'com.example.animal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEyrYeUOhIrnRMCEYmWEO8KXn-J-d8Pk0',
    appId: '1:799126783379:ios:150d1674672d8cb3a3d466',
    messagingSenderId: '799126783379',
    projectId: 'animal-5e97a',
    storageBucket: 'animal-5e97a.appspot.com',
    iosBundleId: 'com.example.animal.RunnerTests',
  );
}
